AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: testing ways of getting secrets
Globals:
    # More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
    Function:
        MemorySize: 1536
        Runtime: java11
        Timeout: 30
        Environment:
          Variables:
#            JAVA_TOOL_OPTIONS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1
            KEY_ID: c266b498-9447-42bc-b057-6aa2e365cba1
            KMS_SECRET: AQICAHixK67pfFbupXwAcICQ86qbs2TVtocTQavzUUoIIigh9gFkbts2lG6sUyMLNKM6EtuaAAAAZDBiBgkqhkiG9w0BBwagVTBTAgEAME4GCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMvGlL9i7fW522fHuKAgEQgCGhGZqdO+Smg8wG/a3X0epV+H2wLs9zxBQEIHbQWA2iiPU=

    Api:
        Cors:
            AllowMethods: "'GET,PUT,POST,DELETE,OPTIONS'"
            AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key'"
            AllowOrigin: "'*'"
            AllowCredentials: "'*'"

Resources:
#    AysecretsFunction:
#        # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
#        Type: AWS::Serverless::Function
#        Properties:
#            CodeUri: aysecrets-api/target/aysecrets-api-1.0.0.zip
#            Handler: com.turnitin.aysecrets.AysecretsGet
#            Policies:
#            - Statement:
#                - Sid: secretsmanagergetsecretpolicy
#                  Effect: Allow
#                  Action:
#                  - secretsmanager:GetSecretValue
#                  Resource: arn:aws:secretsmanager:us-east-2:431036401867:secret:ayacub-test-secret-mfsIjR
#                - Sid: sssmgetparameterpolicy
#                  Effect: Allow
#                  Action:
#                  - ssm:GetParameter
#                  Resource: "*"
#            Events:
#                AysecretsHelloApi:
#                    Type: Api
#                    Properties:
#                        Path: /secret
#                        Method: GET

    AysecretsTestFunction:
      # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
      Type: AWS::Serverless::Function
      Properties:
        CodeUri: aysecrets-api/target/aysecrets-api-1.0.0.zip
        Handler: com.turnitin.aysecrets.AysecretsTestFunctionGet
        Policies:
          - Statement:
              - Sid: secretsmanagergetsecretpolicy
                Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                Resource: arn:aws:secretsmanager:us-east-2:431036401867:secret:ayacub-test-secret-mfsIjR
              - Sid: sssmgetparameterpolicy
                Effect: Allow
                Action:
                  - ssm:GetParameter
                Resource: "*"
        Events:
          AysecretsHelloApi:
            Type: Api
            Properties:
              Path: /test
              Method: GET


    AysecretsSecretManagerFunction:
      # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
      Type: AWS::Serverless::Function
      Properties:
        CodeUri: aysecrets-api/target/aysecrets-api-1.0.0.zip
        Handler: com.turnitin.aysecrets.AysecretsSecretManagerFunctionGet
        Policies:
          - Statement:
              - Sid: secretsmanagergetsecretpolicy
                Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                Resource: arn:aws:secretsmanager:us-east-2:431036401867:secret:ayacub-test-secret-mfsIjR
              - Sid: sssmgetparameterpolicy
                Effect: Allow
                Action:
                  - ssm:GetParameter
                Resource: "*"
        Events:
          AysecretsHelloApi:
            Type: Api
            Properties:
              Path: /secret/sm
              Method: GET

    AysecretsParameterStoreFunction:
      # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
      Type: AWS::Serverless::Function
      Properties:
        CodeUri: aysecrets-api/target/aysecrets-api-1.0.0.zip
        Handler: com.turnitin.aysecrets.AysecretsParameterStoreFunction
        Policies:
          - Statement:
              - Sid: secretsmanagergetsecretpolicy
                Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                Resource: arn:aws:secretsmanager:us-east-2:431036401867:secret:ayacub-test-secret-mfsIjR
              - Sid: sssmgetparameterpolicy
                Effect: Allow
                Action:
                  - ssm:GetParameter
                Resource: "*"
        Events:
          AysecretsHelloApi:
            Type: Api
            Properties:
              Path: /secret/ps
              Method: GET

    AysecretsCacheFunction:
      # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
      Type: AWS::Serverless::Function
      Properties:
        CodeUri: aysecrets-api/target/aysecrets-api-1.0.0.zip
        Handler: com.turnitin.aysecrets.AysecretsCacheFunction
        Policies:
          - Statement:
              - Sid: secretsmanagergetsecretpolicy
                Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                  - secretsmanager:DescribeSecret
                Resource: arn:aws:secretsmanager:us-east-2:431036401867:secret:ayacub-test-secret-mfsIjR
              - Sid: sssmgetparameterpolicy
                Effect: Allow
                Action:
                  - ssm:GetParameter
                Resource: "*"
        Events:
          AysecretsHelloApi:
            Type: Api
            Properties:
              Path: /secret/cache
              Method: GET

    AysecretsKeystoreFunction:
      # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
      Type: AWS::Serverless::Function
      Properties:
        CodeUri: aysecrets-api/target/aysecrets-api-1.0.0.zip
        Handler: com.turnitin.aysecrets.AysecretsKeystoreFunction
        Events:
          AysecretsHelloApi:
            Type: Api
            Properties:
              Path: /secret/ks
              Method: GET
        Policies:
          - KMSDecryptPolicy:
              KeyId: c266b498-9447-42bc-b057-6aa2e365cba1

    AysecretsExtensionFunction:
      # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
      Type: AWS::Serverless::Function
      Properties:
        CodeUri: aysecrets-api/target/aysecrets-api-1.0.0.zip
        Handler: com.turnitin.aysecrets.AysecretsExtensionFunction
        Events:
          AysecretsHelloApi:
            Type: Api
            Properties:
              Path: /secret/ext
              Method: GET
        Layers:
          - arn:aws:lambda:us-east-2:590474943231:layer:AWS-Parameters-and-Secrets-Lambda-Extension:2
        Policies:
          - Statement:
              - Sid: secretsmanagergetsecretpolicy
                Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                Resource: arn:aws:secretsmanager:us-east-2:431036401867:secret:ayacub-test-secret-mfsIjR
              - Sid: sssmgetparameterpolicy
                Effect: Allow
                Action:
                  - ssm:GetParameter
                Resource: "*"


    AysecretsExtensionEuropeFunction:
      # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
      Type: AWS::Serverless::Function
      Properties:
        CodeUri: aysecrets-api/target/aysecrets-api-1.0.0.zip
        Handler: com.turnitin.aysecrets.AysecretsExtensionFunction
        Events:
          AysecretsHelloApi:
            Type: Api
            Properties:
              Path: /secret/ext-eur
              Method: GET
        Layers:
          - arn:aws:lambda:eu-south-1:325218067255:layer:AWS-Parameters-and-Secrets-Lambda-Extension:2
        Policies:
          - Statement:
              - Sid: secretsmanagergetsecretpolicy
                Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                Resource: arn:aws:secretsmanager:us-east-2:431036401867:secret:ayacub-test-secret-mfsIjR
              - Sid: sssmgetparameterpolicy
                Effect: Allow
                Action:
                  - ssm:GetParameter
                Resource: "*"

  #    AysecretsFunction:
  #        # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
  #        Type: AWS::Serverless::Function
  #        Properties:
  #            CodeUri: aysecrets-api/target/aysecrets-api-1.0.0.zip
  #            Handler: com.turnitin.aysecrets.AysecretsGet
  #            Policies:
  #            - Statement:
  #                - Sid: secretsmanagergetsecretpolicy
  #                  Effect: Allow
  #                  Action:
  #                  - secretsmanager:GetSecretValue
  #                  Resource: arn:aws:secretsmanager:us-east-2:431036401867:secret:ayacub-test-secret-mfsIjR
  #                - Sid: sssmgetparameterpolicy
  #                  Effect: Allow
  #                  Action:
  #                  - ssm:GetParameter
  #                  Resource: "*"
  #            Events:
  #                AysecretsHelloApi:
  #                    Type: Api
  #                    Properties:
  #                        Path: /secret
  #                        Method: GET

    AysecretsTestFunction:
      # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
      Type: AWS::Serverless::Function
      Properties:
        CodeUri: aysecrets-api/target/aysecrets-api-1.0.0.zip
        Handler: com.turnitin.aysecrets.AysecretsTestFunctionGet
        Policies:
          - Statement:
              - Sid: secretsmanagergetsecretpolicy
                Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                Resource: arn:aws:secretsmanager:us-east-2:431036401867:secret:ayacub-test-secret-mfsIjR
              - Sid: sssmgetparameterpolicy
                Effect: Allow
                Action:
                  - ssm:GetParameter
                Resource: "*"
        Events:
          AysecretsHelloApi:
            Type: Api
            Properties:
              Path: /test
              Method: GET


    AysecretsSecretManagerFunction:
      # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
      Type: AWS::Serverless::Function
      Properties:
        CodeUri: aysecrets-api/target/aysecrets-api-1.0.0.zip
        Handler: com.turnitin.aysecrets.AysecretsSecretManagerFunctionGet
        Policies:
          - Statement:
              - Sid: secretsmanagergetsecretpolicy
                Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                Resource: arn:aws:secretsmanager:us-east-2:431036401867:secret:ayacub-test-secret-mfsIjR
              - Sid: sssmgetparameterpolicy
                Effect: Allow
                Action:
                  - ssm:GetParameter
                Resource: "*"
        Events:
          AysecretsHelloApi:
            Type: Api
            Properties:
              Path: /secret/sm
              Method: GET

    AysecretsParameterStoreFunction:
      # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
      Type: AWS::Serverless::Function
      Properties:
        CodeUri: aysecrets-api/target/aysecrets-api-1.0.0.zip
        Handler: com.turnitin.aysecrets.AysecretsParameterStoreFunction
        Policies:
          - Statement:
              - Sid: secretsmanagergetsecretpolicy
                Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                Resource: arn:aws:secretsmanager:us-east-2:431036401867:secret:ayacub-test-secret-mfsIjR
              - Sid: sssmgetparameterpolicy
                Effect: Allow
                Action:
                  - ssm:GetParameter
                Resource: "*"
        Events:
          AysecretsHelloApi:
            Type: Api
            Properties:
              Path: /secret/ps
              Method: GET

    AysecretsCacheFunction:
      # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
      Type: AWS::Serverless::Function
      Properties:
        CodeUri: aysecrets-api/target/aysecrets-api-1.0.0.zip
        Handler: com.turnitin.aysecrets.AysecretsCacheFunction
        Policies:
          - Statement:
              - Sid: secretsmanagergetsecretpolicy
                Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                  - secretsmanager:DescribeSecret
                Resource: arn:aws:secretsmanager:us-east-2:431036401867:secret:ayacub-test-secret-mfsIjR
              - Sid: sssmgetparameterpolicy
                Effect: Allow
                Action:
                  - ssm:GetParameter
                Resource: "*"
        Events:
          AysecretsHelloApi:
            Type: Api
            Properties:
              Path: /secret/cache
              Method: GET

    AysecretsKeystoreFunction:
      # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
      Type: AWS::Serverless::Function
      Properties:
        CodeUri: aysecrets-api/target/aysecrets-api-1.0.0.zip
        Handler: com.turnitin.aysecrets.AysecretsKeystoreFunction
        Events:
          AysecretsHelloApi:
            Type: Api
            Properties:
              Path: /secret/ks
              Method: GET
        Policies:
          - KMSDecryptPolicy:
              KeyId: c266b498-9447-42bc-b057-6aa2e365cba1

    AysecretsExtensionFunction:
      # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
      Type: AWS::Serverless::Function
      Properties:
        CodeUri: aysecrets-api/target/aysecrets-api-1.0.0.zip
        Handler: com.turnitin.aysecrets.AysecretsExtensionFunction
        Events:
          AysecretsHelloApi:
            Type: Api
            Properties:
              Path: /secret/ext
              Method: GET
        Layers:
          - arn:aws:lambda:us-east-2:590474943231:layer:AWS-Parameters-and-Secrets-Lambda-Extension:2
        Policies:
          - Statement:
              - Sid: secretsmanagergetsecretpolicy
                Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                Resource: arn:aws:secretsmanager:us-east-2:431036401867:secret:ayacub-test-secret-mfsIjR
              - Sid: sssmgetparameterpolicy
                Effect: Allow
                Action:
                  - ssm:GetParameter
                Resource: "*"


    AysecretsExtensionMiddleEastFunction:
      # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
      Type: AWS::Serverless::Function
      Properties:
        CodeUri: aysecrets-api/target/aysecrets-api-1.0.0.zip
        Handler: com.turnitin.aysecrets.AysecretsExtensionFunction
        Events:
          AysecretsHelloApi:
            Type: Api
            Properties:
              Path: /secret/ext-me
              Method: GET
        Layers:
          - arn:aws:lambda:me-central-1:858974508948:layer:AWS-Parameters-and-Secrets-Lambda-Extension:2
        Policies:
          - Statement:
              - Sid: secretsmanagergetsecretpolicy
                Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                Resource: arn:aws:secretsmanager:us-east-2:431036401867:secret:ayacub-test-secret-mfsIjR
              - Sid: sssmgetparameterpolicy
                Effect: Allow
                Action:
                  - ssm:GetParameter
                Resource: "*"



    AysecretsHelloWorldFunction:
      # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
      Type: AWS::Serverless::Function
      Properties:
        CodeUri: aysecrets-api/target/aysecrets-api-1.0.0.zip
        Handler: com.turnitin.aysecrets.AysecretsHelloWorldFunction
        Events:
          AysecretsHelloApi:
            Type: Api
            Properties:
              Path: /secret/hello
              Method: GET
    AysecretsHelloWorld2Function:
      # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
      Type: AWS::Serverless::Function
      Properties:
        CodeUri: aysecrets-api/target/aysecrets-api-1.0.0.zip
        Handler: com.turnitin.aysecrets.AysecretsHelloWorld2Function
        Events:
          AysecretsHelloApi:
            Type: Api
            Properties:
              Path: /secret/hello2
              Method: GET
# Metadata:
    # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/metadata-section-structure.html
# Parameters:
    # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/parameters-section-structure.html
# Mappings:
    # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/mappings-section-structure.html
# Conditions:
    # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/conditions-section-structure.html
# Outputs:
    # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/outputs-section-structure.html
